name: GitHub Cronjobs

on:
  push:
    paths:
      - "functions/**"
      - ".github/workflows/gh-jobs.yml"
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Build Script
        working-directory: functions
        run: yarn install && yarn build
      - name: Update Docs
        working-directory: functions
        run: node main.js
        env:
          API_KEY_GIAO_HANG_NHANH: ${{ secrets.API_KEY_GIAO_HANG_NHANH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "docs-bot"
          git add ./docs
          git commit -m "update-github-docs" || exit 0
          git push
